spring:
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20

  datasource:
    # ImMemory
    url: jdbc:h2:mem:db
    username: admin
    password:
  h2.console.enabled: true

  data.rest:
    basePath: /api
    returnBodyOnCreate: true


logging:
  level:
    root: WARN
    com.example.diploma: DEBUG
#    org.springframework.security.web.FilterChainProxy: DEBUG